spring:
 datasource:
   driver-class-name:
     com.mysql.cj.jdbc.Driver
   url:
     jdbc:mysql://localhost:3306/limsdb?useUnicode=true&characterEncoding=utf8&useSSL=false&serverTimezone=GMT%2B8
   username:
     root
   password:
     wyq---
mybatis:
  type-aliases-package:
   com.bjdfzh.platformservice.entity
  mapperLocations:
   classpath:mappers/*.xml
  config-location:
     classpath:mybatisconfig.xml